### ISSUE TITLE
brew install fails on bitrise with Xcode-beta (10)

### ISSUE THREAD

**Issue by ericmarkmartin** [yonaskolb/XcodeGen#340]
Either I'm not correctly understanding what is needed fix the issues raised in issues like #283, or the issue has been reintroduced in Xcode-beta 10. This is especially weird because the installation does pass on my local environment with both Xcode 9 and Xcode-beta 10. This is my log from bitrise

```
==> Installing xcodegen from yonaskolb/xcodegen
==> Downloading https://github.com/yonaskolb/XcodeGen/archive/1.10.3.tar.gz
==> Downloading from https://codeload.github.com/yonaskolb/XcodeGen/tar.gz/1.10.
#############                                                             19.4%
######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/xcodegen/1.10.3
Last 15 lines from /Users/vagrant/Library/Logs/Homebrew/xcodegen/01.make:
Cloning https://github.com/kylef/Commander.git
Resolving https://github.com/kylef/Commander.git at 0.8.0
Cloning https://github.com/xcodeswift/xcproj.git
Resolving https://github.com/xcodeswift/xcproj.git at 4.3.0
Cloning https://github.com/yonaskolb/JSONUtilities.git
Resolving https://github.com/yonaskolb/JSONUtilities.git at 4.0.2
Cloning https://github.com/onevcat/Rainbow.git
Resolving https://github.com/onevcat/Rainbow.git at 3.1.4
Cloning https://github.com/yonaskolb/Spectre.git
Resolving https://github.com/yonaskolb/Spectre.git at 0.8.1
Cloning https://github.com/tadija/AEXML.git
Resolving https://github.com/tadija/AEXML.git at 4.3.0
Cloning https://github.com/JohnSundell/ShellOut.git
Resolving https://github.com/JohnSundell/ShellOut.git at 2.1.0
make: *** [build] Error 1
If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
yonaskolb/xcodegen
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:222:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:180:in `open_api'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:294:in `search'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:227:in `search_issues'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:240:in `issues_for_formula'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `issues'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:418:in `dump'
from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
[09:38:38]: Exit status: 1
```

**Comment by yonaskolb** [comment]
I've submitted the homebrew formula to homebrew core. We'll see if that changes anything. Perhaps the pre-bottled installs will work. https://github.com/Homebrew/homebrew-core/pull/30079

**Comment by ericmarkmartin** [comment]
That’s an interesting thought. Brew tends to be pretty quick, so hopefully it gets merged soon.

**Comment by yonaskolb** [comment]
The formula is now in homebrew core and I've removed the one in this repo.
Can you please try again?
To make sure you're getting the official formula run this first
```
brew untap yonaskolb/xcodegen
```

If it doesn't install at least you will get proper errors now instead of a curl error

**Comment by ericmarkmartin** [comment]
The pre-bottled install works perfectly. Thanks so much for your responsiveness!

**Comment by yonaskolb** [comment]
Great!
